version: "3"
services:
  docker:
    image: docker:dind
    networks:
      - a-line
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - "docker-certs:/certs"
      - "a-line-workdir:/tmp/example"
    ports:
      - "2376:2376"
    command:
      - --storage-driver
      - overlay2

  a-line-cli:
    image: hamstershare/a-line-cli:latest
    networks:
      - a-line
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - "docker-certs:/certs/client:ro "
      - "a-line-workdir:/tmp/example"
    ports:
      - "8080:8080"


volumes:
  docker-certs: {}
  a-line-workdir: {}

networks:
  a-line: {}
