version: 1.0
name: my-test2
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: https://gitee.com/mohaijiang/spring-boot-example.git
          branch: master
  code-compile:
    needs:
      - git-clone
    steps:
      - name: save artifactory
        use: ipfs
        with:
          path: README.md