name: "wails build"
on:
  push:
    branches:
      - main
      - develop

jobs:
  package:
    strategy:
      matrix:
        platform: [ ubuntu-latest,macos-latest,windows-latest ]
        go-version: [1.19]
        node-version: [18]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # You may need to manually build you frontend manually here, unless you have configured frontend build and install commands in wails.json.
      - name: frontend
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: |
          git clone https://github.com/hamster-shared/a-line.git -b develop
          cd a-line
          npm install && npm run build
          cp -r dist ../pkg/controller
      - name: frontend
        if: matrix.platform == 'windows-latest'
        run: |
          git clone https://github.com/hamster-shared/a-line.git -b develop
          cd a-line
          npm install && npm run build
          copy .\dist ..\pkg\controller
      - name: go build
        run: go mod tidy && go build -o a-line-cli

      - name: upload artifacts linux
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: a-line-cli-v1.0.0-linux-amd64.zip
          path: a-line-cli
      - name: upload artifacts linux
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: a-line-cli-v1.0.0-darwin-amd64.zip
          path: a-line-cli

      - name: Login to Docker Hub
        if: matrix.platform == 'ubuntu-latest'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: build image
        if: matrix.platform == 'ubuntu-latest'
        run : |
          docker build -t hamstershare/a-line-cli:latest .
          docker push hamstershare/a-line-cli:latest
